name: Deploy Node.js App to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust to your required Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm start # Ensure your package.json has a build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www  # Output directory to deploy
